server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/window?autoReconnect=true&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: gw8588279
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true